version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    env_file:
      - ./variables.env
    volumes:
      - .:/app  
    depends_on:
      - db
    restart: unless-stopped  

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    env_file:
      - ./variables.env
    volumes:
      - ./db_data:/var/lib/postgresql/data
    restart: unless-stopped  



