"""courses feature

Revision ID: 42ac8f1fbc3f
Revises: 8972fbebe69e
Create Date: 2024-10-23 11:26:15.891023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42ac8f1fbc3f'
down_revision: Union[str, None] = '8972fbebe69e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('video_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'video_url')
    # ### end Alembic commands ###
